language: elixir
elixir:
  - 1.3.2
otp_release:
  - 18.1
  - 18.2
  - 18.3
services:
  - mysql
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS="+T 9"
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - ECTO_POOL=sbroker MIX_ENV=mysql mix test
